# -*- coding: utf-8 -*-
# src/core/product.py
"""
Product Model - Repräsentiert einen programmierbaren Controller
- Speichert alle Konfigurationen für ein Produkt
- Wird in products.db gespeichert
"""

from dataclasses import dataclass, asdict
from datetime import datetime
from typing import List, Dict, Optional


@dataclass
class ProgrammingStep:
    """Repräsentiert einen Programmier-Schritt."""
    number: int              # 1-6
    name: str               # "Chip Erase"
    description: str        # "Löscht den kompletten Flash"
    enabled: bool           # True/False
    
    def __repr__(self):
        status = "✅" if self.enabled else "❌"
        return f"{status} {self.number}. {self.name}"


@dataclass
class Product:
    """
    Repräsentiert ein programmierbares Produkt.
    
    Beispiel:
        product = Product(
            id=1,
            name="Mainboard v1.0",
            description="Hauptplatine Revision 1.0",
            controller="AT32UC3A1512",
            bootloader_hex="firmware/v1.0/boot.hex",
            userpage_hex="firmware/v1.0/userpage.hex",
            fuse_bits_value="XXXXXXXX",
            steps=[
                ProgrammingStep(1, "Chip Erase", "...", True),
                ProgrammingStep(2, "User Page Erase", "...", True),
                ...
            ],
            atprogram_path="C:/atprogram.exe",
            atbackend_path="C:/atbackend.exe",
            objcopy_path="C:/avr32-objcopy.exe",
            created_at=datetime.now(),
            updated_at=datetime.now(),
            last_programmed=None
        )
    """
    
    # Identifikation
    id: Optional[int]                    # Auto-generated by DB
    name: str                            # "Mainboard v1.0"
    description: str                     # Optional Beschreibung
    
    # Hardware-Konfiguration
    controller: str                      # "AT32UC3A1512"
    bootloader_hex: str                  # Pfad zur HEX-Datei
    userpage_hex: str                    # Pfad zur User-Page HEX
    fuse_bits_value: str                 # "F675FFFF"
    
    # Programmier-Schritte
    steps: List[ProgrammingStep]         # [Step1, Step2, ..., Step6]
    
    # Tool-Konfiguration
    atprogram_path: str                  # Pfad zu atprogram.exe
    atbackend_path: str                  # Pfad zu atbackend.exe
    objcopy_path: str                    # Pfad zu avr32-objcopy.exe
    
    # Metadaten
    created_at: datetime                 # Wann erstellt
    updated_at: datetime                 # Wann zuletzt geändert
    last_programmed: Optional[datetime]  # Wann zuletzt programmiert
    
    def __repr__(self):
        return f"Product(name={self.name}, controller={self.controller})"
    
    def to_dict(self) -> dict:
        """Konvertiert Product zu Dictionary für DB-Speicherung."""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "controller": self.controller,
            "bootloader_hex": self.bootloader_hex,
            "userpage_hex": self.userpage_hex,
            "fuse_bits_value": self.fuse_bits_value,
            "steps": [asdict(step) for step in self.steps],
            "atprogram_path": self.atprogram_path,
            "atbackend_path": self.atbackend_path,
            "objcopy_path": self.objcopy_path,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "last_programmed": self.last_programmed.isoformat() if self.last_programmed else None,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "Product":
        """Erstellt Product aus Dictionary."""
        steps = [ProgrammingStep(**step) for step in data.get("steps", [])]
        
        return cls(
            id=data.get("id"),
            name=data.get("name"),
            description=data.get("description", ""),
            controller=data.get("controller"),
            bootloader_hex=data.get("bootloader_hex"),
            userpage_hex=data.get("userpage_hex"),
            fuse_bits_value=data.get("fuse_bits_value"),
            steps=steps,
            atprogram_path=data.get("atprogram_path"),
            atbackend_path=data.get("atbackend_path"),
            objcopy_path=data.get("objcopy_path"),
            created_at=datetime.fromisoformat(data.get("created_at", datetime.now().isoformat())),
            updated_at=datetime.fromisoformat(data.get("updated_at", datetime.now().isoformat())),
            last_programmed=datetime.fromisoformat(data.get("last_programmed")) if data.get("last_programmed") else None,
        )
    
    @staticmethod
    def create_default_steps() -> List[ProgrammingStep]:
        """Erstellt Standard-Programmier-Schritte."""
        return [
            ProgrammingStep(1, "Chip Erase", "Löscht den kompletten Flash", True),
            ProgrammingStep(2, "User Page Erase", "Löscht die User Page", True),
            ProgrammingStep(3, "User Page Write", "Schreibt Werte in User Page", True),
            ProgrammingStep(4, "Flash Write", "Schreibt Bootloader", True),
            ProgrammingStep(5, "Fuse Bits", "Setzt Fuse Bits", True),
            ProgrammingStep(6, "Security Bit", "Setzt Security Bit", False),
        ]