# -*- coding: utf-8 -*-
# src/core/product.py
"""
Product Model - Repräsentiert einen programmierbaren Controller
"""

from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class ProgrammingStep:
    """Repräsentiert einen Programmier-Schritt."""
    number: int              # 1-6
    name: str               # "Chip Erase"
    description: str        # "Löscht den kompletten Flash"
    enabled: bool           # True/False
    
    def __repr__(self):
        status = "✅" if self.enabled else "❌"
        return f"{status} {self.number}. {self.name}"


@dataclass
class Product:
    """Repräsentiert ein programmierbares Produkt."""
    
    id: Optional[int]                    # Auto-generated by DB
    name: str                            # "Mainboard v1.0"
    description: str                     # Optionale Beschreibung
    
    # Hardware-Konfiguration
    controller: str                      # "AT32UC3A1512"
    bootloader_hex: str                  # Pfad zur HEX-Datei
    userpage_hex: str                    # Pfad zur User-Page HEX
    fuse_bits_value: str                 # "F675FFFF"
    
    # Programmier-Schritte
    steps: List[ProgrammingStep]         # [Step1, Step2, ..., Step6]
    
    # Tool-Konfiguration
    atprogram_path: str                  # Pfad zu atprogram.exe
    atbackend_path: str                  # Pfad zu atbackend.exe
    objcopy_path: str                    # Pfad zu avr32-objcopy.exe
    
    # Metadaten
    created_at: datetime                 # Wann erstellt
    updated_at: datetime                 # Wann zuletzt geändert
    last_programmed: Optional[datetime]  # Wann zuletzt programmiert
    
    def __repr__(self):
        return f"Product(name={self.name}, controller={self.controller})"
    
    @staticmethod
    def create_default_steps() -> List[ProgrammingStep]:
        """Erstellt Standard-Programmier-Schritte."""
        return [
            ProgrammingStep(1, "Chip Erase", "Löscht den kompletten Flash", True),
            ProgrammingStep(2, "User Page Erase", "Löscht die User Page", True),
            ProgrammingStep(3, "User Page Write", "Schreibt Werte in User Page", True),
            ProgrammingStep(4, "Flash Write", "Schreibt Bootloader", True),
            ProgrammingStep(5, "Fuse Bits", "Setzt Fuse Bits", True),
            ProgrammingStep(6, "Security Bit", "Setzt Security Bit", False),
        ]